apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-billing
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: sys-billing
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: BILLING_ESB_HOST
              value: https://esb.westfieldgrp.corp
            - name: BILLING_WAS_HOST
              value: https://wassvc.westfieldgrp.corp
            - name: BILLING_STS_HOST
              value: https://sso.westfieldgrp.corp
