api.name=sapi-billing
api.id=16888213
api.version=v1
api.host=0.0.0.0
api.port=8081
api.path=/*


externalPrimaryAccount.host=wassvcu.westfieldgrp.corp
response.timeout=10000

#Application Json Logger
json.data.disable.fields=
json.data.mask.fields=

#common errorhandling json logger
ceh.data.disable.fields=
ceh.data.mask.fields=

truststore.path=mulesoft_truststore.jks

pasm.id.billing=1988

ping.fed=idpa1-test.westfieldgrp.corp
ping.fed.port=9543


saml.wsa.address=urn:sts:mulesoft:unt:to:saml:nonprod

#primary Account config
primaryAccount.host=dev5esb.westfieldgrp.corp
primaryAccount.path=/esb
