api.name=sapi-billing
api.id=15710690
api.version=v1
api.host=0.0.0.0
api.port=8081
api.path=/*

#Application Json Logger
json.data.disable.fields=
json.data.mask.fields=

#common errorhandling json logger
ceh.data.disable.fields=
ceh.data.mask.fields=

truststore.path=mulesoft_truststore.jks
pasm.id.billing = 1991

externalPrimaryAccount.host=wassvc.westfieldgrp.corp
response.timeout=20000

ping.fed=sso.westfieldgrp.corp
ping.fed.port=9543

ping.host=idpa1-test.westfieldgrp.com


saml.wsa.address=urn:sts:mulesoft:unt:to:saml:prod

#primary Account config
primaryAccount.host=esb.westfieldgrp.corp
primaryAccount.path=/esb