apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-billing
spec:
  template:
    spec:
      containers:
        - name: sys-billing
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: PRIMARY_ACCOUNT_HOST
              value: dev5esb.westfieldgrp.corp
            - name: EXTERNAL_PRIMARY_ACCOUNT_HOST
              value: wassvcu.westfieldgrp.corp
            - name: PING_FED_HOST
              value: idpa1-test.westfieldgrp.corp
