apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-billing
spec:
  template:
    spec:
      containers:
        - name: sys-billing
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: perf
            - name: BILLING_ESB_HOST
              value: http://perfesb.westfieldgrp.corp
            - name: BILLING_WAS_HOST
              value: http://wassvcr.westfieldgrp.corp
            - name: BILLING_STS_HOST
              value: https://idpa1-test.westfieldgrp.corp
