apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: perf-
resources:
  - ../../base
patches:
  - path: deployment.patch.yaml
configMapGenerator:
  - name: billing-config
    behavior: merge
    literals:
      - RESPONSE_TIMEOUT_MS=10000
