apiVersion: v1
kind: Service
metadata:
  name: sys-billing
  labels:
    app: sys-billing
spec:
  selector:
    app: sys-billing
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
